name: Run Postman Collection

on:
  push:
    branches:
      - postman

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman Report
        run: npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: 
          newman run postman/BookingAPI.json  \
          -e postman/dev.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        with:
          name: postman-report
          path: report.html